# Generated by Django 4.2 on 2024-11-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retoshuellascarbono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retosrespuesta',
            name='estado',
            field=models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('PENDIENTE', 'PENDIENTE'), ('APROVADO', 'APROVADO')], default='PENDIENTE', max_length=50),
        ),
    ]
