# Generated by Django 4.2 on 2024-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retoshuellascarbono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retosrespuesta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=50),
        ),
    ]
